"""Initial migration

Revision ID: 2f1b9b953a33
Revises: 
Create Date: 2025-02-10 17:42:23.229407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f1b9b953a33'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('device_name', sa.String(), nullable=False),
    sa.Column('device_type', sa.Enum('android', 'windows', name='devicetype'), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', 'offline', name='status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_device_status_device_type', 'device', ['status', 'device_type'], unique=False)
    op.create_index(op.f('ix_device_id'), 'device', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_device_id'), table_name='device')
    op.drop_index('idx_device_status_device_type', table_name='device')
    op.drop_table('device')
    # ### end Alembic commands ###
